SELECT 
    GW3.EMPRESA,
    GW3.GW3_FILIAL,
    GW3.GW3_TPDF,
    GW3.GW3_CDESP,
    GW3.GW3_SERDF,
    GW3.GW3_NRDF,
    GW3.GW3_DTEMIS,
    GW3.GW3_VLDF,
    GWM.GWM_TPDOC,
    GWM.GWM_CDESP,
    GWM.GWM_SERDOC,
    GWM.GWM_NRDOC,
    GWM.GWM_DTEMIS,
    GWM.GWM_VLFRE1,
    GWM.GWM_PEDAG,
    GWM.GWM_CDTRP,
    GWM.GWM_CCFRET
FROM [STAGE].[gfe].[GW3] GW3
LEFT JOIN [STAGE].[gfe].[GWM] GWM
    ON GW3.EMPRESA = GWM.EMPRESA
   AND GW3.GW3_FILIAL = GWM.GWM_FILIAL
   AND GW3.GW3_CDESP = GWM.GWM_CDESP
   AND GW3.GW3_SERDF = GWM.GWM_SERDOC
   AND GW3.GW3_NRDF = GWM.GWM_NRDOC
   AND GW3.GW3_EMISDF = GWM.GWM_CDTRP
WHERE GWM_CCFRET='23210'
and GW3_DTEMIS > '20250701'