WITH GWM_FILTRADO AS (
    SELECT GWM_NRDC, GWM_SERDC, GWM_NRDOC, GWM_ITEM, GWM_VLFRE1
    FROM [STAGE].[gfe].[GWM]
    WHERE GWM_DTEMIS > '20250816'
    AND GWM_SERDC in ('5','21')
    AND GWM_TPDOC='2'
)
SELECT
    GWM_NRDC AS NotaFiscal,
    GWM_SERDC AS SerieNotaFiscal,
    GWM_NRDOC AS NumCTE,
    SUM(GWM_VLFRE1) AS FreteCobrado,
    COUNT(DISTINCT GWM_ITEM) AS QtdeItens
FROM GWM_FILTRADO
GROUP BY GWM_NRDC, GWM_SERDC, GWM_NRDOC