SELECT      
      GW1.[GW1_DTEMIS],
      GW1.[GW1_SERDC],
      GW1.[GW1_NRDC],
      GW1.[GW1_CDDEST],
      GW1.[GW1_TPFRET],
      GW1.[GW1_NRROM],
      GW1.[GW1_QTVOL],
      GW1.[GW1_PEDCLI],
      GW1.[DataCarga],
      GWH.[GWH_NRCALC],
      GWG.[GWG_QTPESO],
      GWG.[GWG_PESCUB],
      GWG.[GWG_QTITEM],
      GWG.[GWG_VLMERC]
FROM [STAGE].[gfe].[GW1] GW1
LEFT JOIN [STAGE].[gfe].[GWH] GWH
  ON GW1.[GW1_NRDC] = GWH.[GWH_NRDC]
 AND GW1.[GW1_SERDC] = GWH.[GWH_SERDC]
 AND ISNULL(GWH.[D_E_L_E_T_], '') <> '*'
LEFT JOIN [STAGE].[gfe].[GWG] GWG
  ON GWH.[GWH_NRCALC] = GWG.[GWG_NRCALC]
 
WHERE GW1.[GW1_SERDC] = '5'
  AND GW1.[GW1_DTEMIS] BETWEEN '20250617' AND '20250717'
  AND GW1.[GW1_FILIAL] = '15'
  order by GWG_QTPESO DESC
