SELECT 
    GWM_NRDC,
    GWM_SERDC,
    GWM_TPDOC,
    SUM(GWM_VLFRE1) AS Frete_Parte1,
    SUM(GWM_VLFRE2) AS Frete_Parte2,
    SUM(GWM_VLFRE3) AS Frete_Parte3,
    SUM(GWM_VLFRE1 + GWM_VLFRE2 + GWM_VLFRE3) AS Frete_Total
FROM [STAGE].[gfe].[GWM]
WHERE GWM_NRDC = '1019205'
  AND GWM_SERDC = '5'
  AND GWM_TPDOC = '2'
GROUP BY GWM_NRDC, GWM_SERDC, GWM_TPDOC;
