SELECT TOP 1000
    GW6.*,
    GW3.*,
    GW4.*,
    GWM.*
FROM
    [STAGE].[gfe].[GW6] AS GW6
LEFT JOIN
    [STAGE].[gfe].[GW3] AS GW3
    ON GW6.[EMPRESA]     = GW3.[EMPRESA]
    AND GW6.[GW6_EMIFAT] = GW3.[GW3_EMIFAT]
    AND GW6.[GW6_SERFAT] = GW3.[GW3_SERFAT]
    AND GW6.[GW6_NRFAT]  = GW3.[GW3_NRFAT]
    AND GW6.[GW6_DTEMIS] = GW3.[GW3_DTEMFA]
LEFT JOIN 
    [STAGE].[gfe].[GW4] AS GW4
    ON GW3.[GW3_SERDF]   = GW4.[GW4_SERDF]
    AND GW3.[GW3_NRDF]   = GW4.[GW4_NRDF]
    AND GW3.[GW3_DTEMIS] = GW4.[GW4_DTEMIS]
    AND GW3.[GW3_FILIAL] = GW4.[GW4_FILIAL]
    AND GW3.[EMPRESA]    = GW4.[EMPRESA]
LEFT JOIN 
    [STAGE].[gfe].[GWM] AS GWM
    ON GW4.[EMPRESA]     = GWM.[EMPRESA]
    AND GW4.[GW4_FILIAL] = GWM.[GWM_FILIAL]
    AND GW4.[GW4_SERDC]  = GWM.[GWM_SERDC]
    AND GW4.[GW4_NRDC]   = GWM.[GWM_NRDC]
    AND GW4.[GW4_DTEMIS] = GWM.[GWM_DTEMDC]

