WITH GW6_Filtrada AS (
    SELECT *
    FROM [STAGE].[gfe].[GW6]
    WHERE GW6_DTFIN > '20250801'
)

SELECT
    GW6.EMPRESA,
    GW6.GW6_EMIFAT,
    GW6.GW6_SERFAT,
    GW6.GW6_NRFAT,
    GW6.GW6_DTEMIS,
    GW6.GW6_VLFATU,
    GW3.GW3_NRDF,
    GW4.GW4_SERDC,
    GWM.GWM_CCFRET,
    GW3.[GW3_DTEMIS],
    GW3.[GW3_VLDF],
    gw3.[GW3_PESOR],
    GW3.[GW3_PESOC],
    GW3.[GW3_VLDIV]

FROM GW6_Filtrada GW6

LEFT JOIN [STAGE].[gfe].[GW3] GW3
    ON GW6.EMPRESA     = GW3.EMPRESA
   AND GW6.GW6_EMIFAT  = GW3.GW3_EMIFAT
   AND GW6.GW6_SERFAT  = GW3.GW3_SERFAT
   AND GW6.GW6_NRFAT   = GW3.GW3_NRFAT
   AND GW6.GW6_DTEMIS  = GW3.GW3_DTEMFA

LEFT JOIN [STAGE].[gfe].[GW4] GW4
    ON GW3.EMPRESA     = GW4.EMPRESA
   AND GW3.GW3_FILIAL  = GW4.GW4_FILIAL
   AND GW3.GW3_SERDF   = GW4.GW4_SERDF
   AND GW3.GW3_NRDF    = GW4.GW4_NRDF
   AND GW3.GW3_DTEMIS  = GW4.GW4_DTEMIS

LEFT JOIN [STAGE].[gfe].[GWM] GWM
    ON GW4.EMPRESA     = GWM.EMPRESA
   AND GW4.GW4_FILIAL  = GWM.GWM_FILIAL
   AND GW4.GW4_SERDC   = GWM.GWM_SERDC
   AND GW4.GW4_NRDC    = GWM.GWM_NRDC
   AND GW4.GW4_DTEMIS  = GWM.GWM_DTEMDC
   AND GW4.GW4_TPDC='nfs'
   AND GWM.GWM_CCFRET  = '23210'
WHERE GWM.GWM_CCFRET='23210'

