WITH GW3_RELACIONADA AS (
    SELECT 
        GWM.GWM_NRDC AS NumeroNF,
        W.*
    FROM 
        [STAGE].[gfe].[GWM] GWM WITH (NOLOCK)
    INNER JOIN 
        [gfe].[gw3] W WITH (NOLOCK)
        ON W.GW3_NRDF = GWM.GWM_NRDOC
       AND W.GW3_SERDF = GWM.GWM_SERDOC
       AND W.GW3_EMISDF = GWM.GWM_CDTRP
    WHERE 
        GWM.GWM_CCFRET = '23210'
        AND GWM.GWM_DTEMIS BETWEEN '2024-06-01' AND '2025-06-30'
        AND GWM.GWM_SERDC IN ('5','21')
        AND GWM.GWM_TPDOC = '2'
        AND GWM.GWM_NRDC IN ('0259076', '0260971', '0261914', '0261923')
)

SELECT 
    NumeroNF,
    COUNT(*) AS TotalRegistros,
    COUNT(DISTINCT 
        CONCAT_WS('|',
            EMPRESA, GW3_FILIAL, GW3_CDESP, GW3_EMISDF, GW3_SERDF, GW3_NRDF, GW3_DTEMIS, GW3_TPDF, GW3_DTENT,
            GW3_CFOP, GW3_SIT, GW3_USUIMP, GW3_CDREM, GW3_CDDEST, GW3_VLDF, GW3_TAXAS, GW3_FRPESO, GW3_FRVAL,
            GW3_PEDAG, GW3_PDGFRT, GW3_ICMPDG, GW3_PDGPIS, GW3_QTDCS, GW3_QTVOL, GW3_VOLUM, GW3_PESOR, GW3_PESOC,
            GW3_VLCARG, GW3_TRBIMP, GW3_BASIMP, GW3_PCIMP, GW3_VLIMP, GW3_IMPRET, GW3_PCRET, GW3_OBS, GW3_CRDICM,
            GW3_CTE, CAST(CAST(GW3_MOTBLQ AS VARBINARY(MAX)) AS VARCHAR(MAX)), GW3_DTBLQ, GW3_USUBLQ,
            CAST(CAST(GW3_MOTAPR AS VARBINARY(MAX)) AS VARCHAR(MAX)), GW3_DTAPR, GW3_USUAPR, GW3_EMIFAT,
            GW3_SERFAT, GW3_NRFAT, GW3_DTEMFA, GW3_FILFAT, GW3_CDCONS, GW3_ORINR, GW3_ORISER, GW3_ORIDTE,
            GW3_DTFIS, GW3_SITFIS, GW3_DTREC, GW3_SITREC, GW3_BASCOF, GW3_VLCOF, GW3_BASPIS, GW3_MOTFIS,
            GW3_VLPIS, GW3_CRDPC, GW3_MOTREC, GW3_NATFRE, GW3_TPCTB, GW3_DTVNFT, GW3_ORIGEM, GW3_XTPDF,
            GW3_TPCTE, GW3_ACINT, GW3_PRITDF, GW3_CPDGFE, GW3_TES, GW3_CONTA, GW3_ITEMCT, GW3_CC, GW3_SITMLA,
            GW3_MOTMLA, GW3_HRAPR, GW3_CDTPSE, GW3_SITCUS, GW3_DESCUS, GW3_DTCUS, GW3_USUCUS, GW3_MOTCUS,
            GW3_USO, GW3_TPOPER, GW3_VLDIV, GW3_SITDIV, GW3_NMDEST, GW3_TPIMP, DataCarga, HashValue
        )
    ) AS CombinacoesDistintas
FROM GW3_RELACIONADA
GROUP BY NumeroNF
ORDER BY NumeroNF
