WITH FretePorCTE AS (
    SELECT 
        GW3.GW3_NRDF,
        MAX(GW3.GW3_VLDF) AS VALOR_CTE,
        SUM(GWM.GWM_VLFRE1) AS SOMA_FRETE
    FROM [STAGE].[gfe].[GW3] GW3
    LEFT JOIN [STAGE].[gfe].[GWM] GWM
        ON GW3.EMPRESA = GWM.EMPRESA
       AND GW3.GW3_FILIAL = GWM.GWM_FILIAL
       AND GW3.GW3_CDESP = GWM.GWM_CDESP
       AND GW3.GW3_SERDF = GWM.GWM_SERDOC
       AND GW3.GW3_NRDF = GWM.GWM_NRDOC
       AND GW3.GW3_EMISDF = GWM.GWM_CDTRP
    WHERE GWM.GWM_CCFRET = '23210'
      AND GW3.GW3_DTEMIS > '20250701'
    GROUP BY GW3.GW3_NRDF
)
SELECT 
    GW3_NRDF,
    VALOR_CTE,
    SOMA_FRETE,
    ROUND(VALOR_CTE - SOMA_FRETE, 2) AS DIFERENCA,
    CASE 
        WHEN ROUND(VALOR_CTE, 2) = ROUND(SOMA_FRETE, 2) THEN 'OK'
        ELSE 'DIVERGENTE'
    END AS STATUS
FROM FretePorCTE
ORDER BY DIFERENCA DESC;
