WITH FRETE_POR_NRDF AS (
    SELECT 
        GW3.EMPRESA,
        GW3.GW3_FILIAL,
        GW3.GW3_NRDF,
        GW3.GW3_VLDF,
        SUM(ISNULL(GWM.GWM_VLFRE1,0)) AS SOMA_VLFRE1
    FROM [STAGE].[gfe].[GW3] GW3
    LEFT JOIN [STAGE].[gfe].[GWM] GWM
        ON GW3.EMPRESA      = GWM.EMPRESA
       AND GW3.GW3_FILIAL  = GWM.GWM_FILIAL
       AND GW3.GW3_CDESP   = GWM.GWM_CDESP
       AND GW3.GW3_SERDF   = GWM.GWM_SERDOC
       AND GW3.GW3_NRDF    = GWM.GWM_NRDOC
    WHERE GWM.GWM_CCFRET = '23210'
      AND GW3.GW3_DTEMIS > '2025-07-01'
    GROUP BY 
        GW3.EMPRESA,
        GW3.GW3_FILIAL,
        GW3.GW3_NRDF,
        GW3.GW3_VLDF
)
SELECT 
    EMPRESA,
    GW3_FILIAL,
    GW3_NRDF,
    GW3_VLDF,
    SOMA_VLFRE1,
    ROUND(GW3_VLDF - SOMA_VLFRE1, 2) AS DIFERENCA,
    CASE 
        WHEN ROUND(GW3_VLDF, 2) = ROUND(SOMA_VLFRE1, 2) THEN 'OK'
        ELSE 'DIVERGENTE'
    END AS STATUS
FROM FRETE_POR_NRDF
WHERE ROUND(GW3_VLDF, 2) <> ROUND(SOMA_VLFRE1, 2);
